### ISSUE TITLE
Criar cadastro de dependentes

### ISSUE THREAD

**Issue by byronkamal** [mecassauro/covinfo-backend#37]
**Descrição**
Devido ao desenvolvimento do app, foram encontradas algumas mudanças necessárias no back-end e dentre elas está a criação e estruturação de uma rota para cadastro somente de dependentes.

**Tasks**
- [x] Acrescentar **novos campos** relacionados ao **endereço** e **geoloc** na _migration_ de _person_
- [x] Criar _model_ de Dependente
- [x] Acrescentar na _Controller form_ métodos relacionados ao cadastro de dependentes
- [x] Reorganizar a forma de cadastro de dependente na _Controller_ de _forms_
- [x] Criar nova rota para cadastro de dependente

**Contexto adicional**
Abaixo estão exemplos de JSON's que devem ser enviados nas rotas de responsável e de dependente:
- Cadastro de Responsável:
```
{
    "user_id": 1,
    "document_number": 9929999999,
    "birth_date": "1995-09-05",
    "nationality": "Brasil",
    "birth_city": "São Paulo",
    "birth_state": "São Paulo",
    "sex": "M",
    "breed": "Pardo",
    "mother_name": "Mônica Rocha",
    "father_name": "Renato Raimundo",
    "quantity_per_home": 2,
    "phone_number": 2020202020202020,
    "phone_code": 61,
    "zip_code": 7555555555,
    "city": "TaguaYork",
    "street": "Rua 01 São José ",
    "house_number": "Casa 10",
    "home_situation": "Própria",
    "state": "TT",
    "comorbidities": [1, 2],
    "lat": "45.2355421",
    "lng": "-15.321256" 		
}
```

- Cadastro  de dependente:
```
{
     "provider_user_id": 2,
     "name":"Paulo",
    "phone_number": 123456789,
    "phone_code": 61,
    "document_number": 9929999999,
    "birth_date": "1995-09-05",
    "nacionality": "Brasil", 
    "birth_city": "São Paulo",
    "birth_state": "São Paulo",
    "sex": "M",
    "breed": "Pardo",
    "mother_name": "Mônica Rocha",
    "father_name": "Renato Raimundo",
    "comorbidities": [1, 2]
}
```
